# Generated by Django 5.0.6 on 2024-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_category_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExelFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_updload', models.FileField(upload_to='excel')),
            ],
        ),
    ]
